## Artificial Neural Network


### Importing libraries

In [9]:
import pandas as pd
import numpy as np
import tensorflow as tf
#Information about the dataset
#Column 1: Temperature (°C)
#Column 2: Pressure (milibar)
#Column 3: Humidity
#Column 4: Exhaust Vacuum (cm Hg)
#Column 5: Net electrical output (MW/h)

##Data Preprocessing

### Importing the dataset

In [10]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


##Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
#Activation function Rectifier

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 1))
#No activation function because we are doing regression, the AF are more usefull for classification

## Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer = "adam", loss = "mean_squared_error")
#Adam performs SGD (Stochastic gradient descent)

### Training the ANN model on the Training set

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 116128.5148
Epoch 2/100
240/240 [==============================] - 0s 980us/step - loss: 1304.3921
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 480.5950
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 477.3682
Epoch 5/100
240/240 [==============================] - 0s 986us/step - loss: 452.2976
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 431.7132
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 415.5189
Epoch 8/100
240/240 [==============================] - 0s 997us/step - loss: 396.0316
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 372.6004
Epoch 10/100
240/240 [==============================] - 0s 943us/step - loss: 342.3387
Epoch 11/100
240/240 [==============================] - 0s 986us/step - loss: 309.7219
Epoch 12/100
240/240 [==============================] - 0s 9



### Results of test set prediction

In [21]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[432.01 431.23]
 [463.03 460.01]
 [466.51 461.14]
 ...
 [473.75 473.26]
 [440.56 438.  ]
 [459.75 463.28]]
